---
apiVersion: v1
kind: Service
metadata:
  labels:
    project: flower
  name: flower
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 5555
      protocol: TCP
      targetPort: 5555
  selector:
    project: flower

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: flower
  name: flower
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: flower
  template:
    metadata:
      labels:
        project: flower
    spec:
      containers:
      - name: flower
        image: mher/flower:latest
        command: ["celery"]
        args: ["--broker", "redis://:$(REDIS_PASS)@redis:6379/0", "flower"]
        ports:
        - containerPort: 5555
        env:
        - name: FLOWER_BASIC_AUTH
          value: "user:pass"
        - name: FLOWER_URL_PREFIX
          value: "flower"
